# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.9
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
- pip install --upgrade pip
- python setup.py install

# Command to run tests, e.g. python setup.py test
script: pytest tests

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - python3.9
      env:
        - C_COMPILER="gcc-7", CXX_COMPILER="g++-7"

before_install:
  - pyenv global $(pyenv whence 2to3)
  - pip install pipenv
  - export MPI_BUILD_DIR=$TRAVIS_BUILD_DIR/openmpi-build
  - export MPI_VERSION="3.1"
  - export MPI_FULL_VERSION="3.1.3"

install:
  # Non-cached builds can take some time. Tell Travis not to time out (30 min should be plenty).
  - source ci/install-openmpi.sh
  - echo $MPI_CC
  - echo $MPI_CXX
  - echo $MPI_EXEC
  - env MPICC=$MPI_CC pipenv install --skip-lock

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: chto
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: chto/linna
    python: 3.9
