name: linna

channels:
    - anaconda

dependencies:
    - python==3.9
    - pip:
        - pyyaml
        - sphinx-gallery
        - sphinxcontrib-napoleon
        - sphinxcontrib-bibtex
        - sphinxcontrib-inlinesyntaxhighlight
        - m2r
